---
title: "Assignment2"
author: "Vienna Saccomanno"
date: "2/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}

library(tidyverse)
library(scales)

```

##Task 1. Cetaceans in Captivity

```{r get_data}
cetaceans<- read_csv("captive_cetacean.csv")
```

```{r wrangle}

cod<- cetaceans %>%
  filter(acquisition %in% c("Rescue", "Capture", "Born")) %>% 
  mutate(acquisition = recode_factor(acquisition,
   'Rescue' = 'Rescued', 'Born' = 'Born in Captivity', 'Capture' = 'Captured')
  ) 
 
cod$originDate = as.Date(as.character(cod$originDate), format = "%m/%d/%y", "%y")
View(cod)

cod_viz<- cod %>% 
  ggplot(aes(x=originDate, fill=as.factor(acquisition)))+
                   geom_histogram(alpha=0.7, bins = 90, color= "black", linetype = "solid") +
  scale_fill_manual(name= "Acquisition\nType", values = c("Captured" = "red",
                              "Born in Captivity"="yellow",
                              "Rescued" = "blue"))+
  scale_x_date(breaks = date_breaks("10 years"), 
               labels = date_format("%Y")) + 
  scale_y_discrete(limits=seq(0,170,20))+
  labs(x= '',
       y= 'Number of Cetaceans')+
  theme_classic()
 
cod_viz

```


##Task 2. Parameter Estimation - Wild Fish Catch
```{r get_data2}
#Read-in catch data
catch<- read_csv("fish_catch.csv")

#Setting "Year" to a sequence of numbers
catch_seq<- catch %>% 
  mutate("seq"= seq(from=0, to=62)) 
```

```{r exploratory graph}

#Making an exploratory graph to estimate the structure of the data
ggplot(catch_seq, aes(x=seq, y=Wild_Catch))+
  geom_point()+
  theme(axis.text.x=element_text(angle=90, hjust=1))


#Data look non-linear, and somewhat logistic
Bestimate<- (90 - 15)/15

#Slope of natural log (y=e^rt -> ln(y) = rt) = r. Looking at the graph, 1950-1970 (i.e. 1-20) was the exponential catch.

#Estimate r (the catch rate). Isolate the first 20 points
r_est <- catch_seq %>%
  filter(seq<21) 

#Make sure the log is linear
ggplot(r_est, aes(x=seq, y=log(Wild_Catch)))+
  geom_point()

#Estimate r
lm(log(Wild_Catch) ~seq, data=r_est)
#r initial = 0.05749

```

Recall logistic growth equation: 

N(t) = A/(1+Be^-rt)
# Estimate for K/A: ~ 90
# Estimate for N0: ~ 15
# Estimate for B: ~ 5
# Estimate for r: ~0.05749
BEstimate <- (90 - 15)/15 # BEstimate = 5

```{r nls}
#Model fitting
catch_fit <- nls(Wild_Catch ~ A/(1+B*exp(-r*seq)), 
                start = list(A = 90, B = 5, r = 0.05749), 
                data = catch_seq, trace = TRUE) 

#Converging at 1365.143; A =100.27828, B= 4.31634, r=0.06989 
```

```{r predicting}

A <- coef(catch_fit)[1]
B <- coef(catch_fit)[2]
r <- coef(catch_fit)[3]

#Create a new sequence of time values (time_seq)
time_seq <- seq(0,62, length = 100)

#Using the parameters (A, B, and r) and the time sequence, predict the catch for the logistic growth model
catch_pred <- A/(1+B*exp(-r*time_seq)) # Logistic growth model

#Binding together the time sequence data and the predictions data into a new data frame
pred_df <- data.frame(time_seq, catch_pred)

```

```{r graphing_pred}

ggplot(catch_seq, aes(x = seq, y = Wild_Catch)) + 
  geom_point(colour = "blue", size = 3) + 
  theme_bw() +
  geom_line(data = pred_df, aes(x = time_seq, y = catch_pred), colour = "orange", size = 1) + 
  xlab("Year") +
  ylab("Catch") +
  ggtitle("Wild Catch 1950-2012")

```

